name: Deploy API
on:
  push:
    paths:
      - 'workspace/apis/**'
    branches:
      - main
jobs:
  Deploy_API:
    runs-on: [self-hosted, macOS]
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Deploy to APIGateway
      run: |
        pwd
        for file in ./../../../workspace/apis/*; do echo $file ; done
        for file in ./../../../workspace/apis/*; do curl -i -X POST -H "Content-Type: text/plain" --data-binary @$file http://localhost:8080/deploy; done
  Run_Test:
    needs: Deploy_API
    runs-on: [self-hosted, macOS]
    steps:
    - name: Running Tests
      run: |
        pwd
        cd ./../../../../api-studio-demo/apistudio
        pwd
        ./gradlew test
    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Junit Report
        path: ${{github.workspace}}\apistudio\build\reports\tests\test
